### ISSUE TITLE
高速HID设备，设置最大包长为1024，发送时只能抓到64字节

### ISSUE THREAD

**Issue by ericQiang** [CherryUSB/cherryusb_ch32v307#1]
问题解决，是因为bushound设置的抓取长度为64字节。改大就行了。

**Comment by sakumisu** [comment]
好的，觉得可以的话，不妨给个 star哦

**Comment by ericQiang** [comment]
必须Star

sakumisu ***@***.***> 于2022年10月28日周五 21:45写道：

**Comment by sakumisu** [comment]
谢谢， 主要是这个仓库哦：https://github.com/sakumisu/CherryUSB

**Comment by ericQiang** [comment]
好的，已经star

**Comment by sakumisu** [comment]
底下有交流群，可以加下
